# Generated by Django 6.0.3 on 2026-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='department_logos/'),
        ),
    ]
