# Generated by Django 6.0.3 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bracketteam_bracketmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(
                choices=[
                    ('upcoming', 'Upcoming'),
                    ('active', 'Active'),
                    ('completed', 'Completed'),
                    ('inactive', 'Deactivated'),
                ],
                default='upcoming',
                max_length=20,
            ),
        ),
    ]
