# Generated by Django 6.0.3 on 2026-05-17 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('score_team_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('judges_names', models.CharField(blank=True, default='', max_length=500)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('ocr_image', models.ImageField(blank=True, null=True, upload_to='scoresheets/ocr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresheets', to='events.event')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresheets', to='events.bracketmatch')),
                ('tabulator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_scoresheets', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_scoresheets', to='events.bracketteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
