# Generated by Django 6.0.3 on 2026-05-23 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_candidatenumber_chairperson_contestant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_judges',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name__iexact', 'Judge'), ('groups__name__iexact', 'Judges'), _connector='OR'), related_name='judging_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
