# Generated by Django 6.0.3 on 2026-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_judge_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scoring_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='tournament_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
