# Generated by Django 6.0.3 on 2026-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_scoring_method_event_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketteam',
            name='is_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bracketteam',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='bracket_locked',
            field=models.BooleanField(default=False),
        ),
    ]
