# Generated by Django 6.0.3 on 2026-06-17 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_candidate_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='champion_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='first_runner_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='second_runner_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='assigned_judges',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name__iexact', 'Judge'), ('groups__name__iexact', 'Judges'), ('groups__name__iexact', 'Scorer'), _connector='OR'), related_name='judging_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
