# Generated by Django 5.2.15 on 2026-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_registrycandidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='registrycandidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
