# Generated by Django 6.0.3 on 2026-08-03 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_scoresheet_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, default='EventTab', max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('academic_year', models.CharField(blank=True, default='', max_length=40)),
                ('intramurals_name', models.CharField(blank=True, default='', max_length=200)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=False)),
                ('password_require_number', models.BooleanField(default=False)),
                ('password_require_symbol', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=0)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('email_notifications', models.BooleanField(default=True)),
                ('mobile_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('notification_config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
