# Generated by Django 6.0.3 on 2026-08-03 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('report_type', models.CharField(max_length=80)),
                ('export_format', models.CharField(blank=True, default='', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='admin_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin report history',
                'verbose_name_plural': 'Admin report history',
                'ordering': ['-created_at'],
            },
        ),
    ]
