# Generated by Django 5.2.15 on 2026-08-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_multiple_stage_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scoresheet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to='events.scoresheettemplate'),
        ),
        migrations.AddField(
            model_name='scoresheettemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
