# Generated by Django 5.2.15 on 2026-08-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_scoresheet_description_and_event_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketmatch',
            name='dependency_label',
            field=models.CharField(blank=True, default='', help_text='e.g. Winner of Game 1 vs Winner of Game 2', max_length=200),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='is_automatic_advance',
            field=models.BooleanField(default=False, help_text='True for Automatic Advance (BYE) slots — not an actual match.'),
        ),
        migrations.AddField(
            model_name='bracketmatch',
            name='playing_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorer_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='pairing_method',
            field=models.CharField(default='random_draw', help_text='random_draw | seeded_draw | manual_pairing', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='result_entry_format',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_custom_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
