# Generated by Django 5.2.15 on 2026-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_match_event_sport_pairing_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Intramurals season / academic year this event belongs to.', max_length=40),
        ),
    ]
