# Generated by Django 5.2.15 on 2026-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_event_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pageant_config',
            field=models.JSONField(blank=True, default=dict, help_text='Pageant wizard metadata: format, categories, awards, pairs, etc.'),
        ),
        migrations.AddField(
            model_name='event',
            name='special_event_type',
            field=models.CharField(blank=True, default='', help_text='Subtype when category is Special Event (e.g. pageant).', max_length=40),
        ),
    ]
