# Generated by Django 5.2.15 on 2026-09-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_criteria_event_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionSubcriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('display_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='events.criterion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventScoringSubcriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('display_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='events.eventscoringcriterion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriteriaSubcriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=4, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriterion_scores', to='events.criteriascoresubmission')),
                ('subcriterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.eventscoringsubcriterion')),
            ],
            options={
                'ordering': ['subcriterion__display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeSubcriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriterion_scores', to='events.judgescore')),
                ('subcriterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.criterionsubcriterion')),
            ],
            options={
                'ordering': ['subcriterion__display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='criterionsubcriterion',
            constraint=models.UniqueConstraint(fields=('criterion', 'display_order'), name='unique_mobile_subcriterion_order'),
        ),
        migrations.AddConstraint(
            model_name='eventscoringsubcriterion',
            constraint=models.UniqueConstraint(fields=('criterion', 'display_order'), name='unique_event_subcriterion_order'),
        ),
        migrations.AddConstraint(
            model_name='criteriasubcriterionscore',
            constraint=models.UniqueConstraint(fields=('submission', 'subcriterion'), name='unique_submission_subcriterion_score'),
        ),
        migrations.AddConstraint(
            model_name='judgesubcriterionscore',
            constraint=models.UniqueConstraint(fields=('judge_score', 'subcriterion'), name='unique_judge_subcriterion_score'),
        ),
    ]
