# Generated by Django 5.2.15 on 2026-09-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_optional_subcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
