"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from .api_views import health_check
from .views import (
    admin_brackets,
    admin_generate_bracket,
    admin_view_bracket,
    admin_delete_bracket,
    admin_get_bracket_teams,
    admin_departments,
    admin_teams,
    admin_candidates,
    admin_create_team,
    admin_view_team,
    admin_edit_team,
    admin_delete_team,
    admin_create_candidate,
    admin_view_candidate,
    admin_edit_candidate,
    admin_delete_candidate,
    admin_dashboard,
    admin_generate_report,
    admin_bulk_delete_events,
    admin_delete_event,
    admin_edit_event,
    admin_tab_create,
    admin_tab_update,
    admin_tab_delete,
    admin_manage_account,
    admin_tabulator_accounts,
    admin_judge_scorer_accounts,
    admin_manage_events,
    admin_event_selector,
    admin_match_events,
    admin_match_event_preview,
    admin_match_event_detail,
    admin_delete_match_event,
    admin_criteria_events,
    admin_criteria_event_detail,
    admin_delete_criteria_event,
    admin_scoresheets,
    admin_scoresheet_template_save,
    admin_scoresheet_template_delete,
    admin_scoresheet_template_duplicate,
    admin_scoresheet_preview,
    admin_scoresheet_sample_pdf,
    activate_admin,
    admin_create_department,
    admin_view_department,
    admin_edit_department,
    admin_delete_department,
    admin_bulk_delete_departments,
    create_assignment_account,
    next_assignment_access_code,
    create_admin,
    deactivate_admin,
    delete_assignment_account,
    bulk_delete_assignment_accounts,
    delete_admin,
    login_view,
    logout_view,
    superadmin_reports,
    generate_superadmin_report,
    tabulator_save_scores,
    tabulator_generate_report,
    tabulator_verify_lock,
    tabulator_request_changes,
    tabulator_approve_result,
    tabulator_reject_result,
    tabulator_activity_logs_feed,
    update_assignment_account,
    update_admin,
)
from .faculty_views import (
    faculty_dashboard,
    faculty_my_events,
    faculty_event_manage,
    faculty_schedules,
    faculty_scoresheets,
    faculty_scoresheet_item_pdf,
    faculty_scoresheet_generate,
    faculty_results_review,
    faculty_leaderboard,
    faculty_export_schedule,
    faculty_scoresheet_pdf,
    faculty_match_result,
    faculty_results_action,
    faculty_stage_confirm,
)
from .superadmin_views import (
    superadmin_dashboard as sa_dashboard,
    superadmin_users,
    superadmin_user_detail,
    superadmin_user_create,
    superadmin_user_update,
    superadmin_user_reset_password,
    superadmin_user_set_active,
    superadmin_user_delete,
    superadmin_event_monitoring,
    superadmin_event_detail,
    superadmin_leaderboard,
    superadmin_leaderboard_export,
    superadmin_settings,
    superadmin_settings_save,
    superadmin_profile,
    superadmin_profile_update,
    superadmin_change_password,
    superadmin_activity_logs as sa_activity_logs,
)

urlpatterns = [
    path('api/health/', health_check, name='health_check'),
    path('api/auth/', include('accounts.urls')),
    path('api/events/', include('events.api_urls')),
    path('', login_view, name='home'),
    path('login/', login_view, name='login'),
    path('faculty/dashboard/', faculty_dashboard, name='faculty_dashboard'),
    path('faculty/events/', faculty_my_events, name='faculty_my_events'),
    path('faculty/events/<int:event_id>/', faculty_event_manage, name='faculty_event_manage'),
    path('faculty/events/<int:event_id>/schedule/export/', faculty_export_schedule, name='faculty_export_schedule'),
    path('faculty/events/<int:event_id>/scoresheets/<int:match_id>/pdf/', faculty_scoresheet_pdf, name='faculty_scoresheet_pdf'),
    path('faculty/events/<int:event_id>/matches/<int:match_id>/result/', faculty_match_result, name='faculty_match_result'),
    path('faculty/events/<int:event_id>/results/action/', faculty_results_action, name='faculty_results_action'),
    path('faculty/events/<int:event_id>/stages/confirm/', faculty_stage_confirm, name='faculty_stage_confirm'),
    path('faculty/schedules/', faculty_schedules, name='faculty_schedules'),
    path('faculty/scoresheets/', faculty_scoresheets, name='faculty_scoresheets'),
    path('faculty/scoresheets/<int:event_id>/<str:item_key>/pdf/', faculty_scoresheet_item_pdf, name='faculty_scoresheet_item_pdf'),
    path('faculty/scoresheets/<int:event_id>/<str:item_key>/generate/', faculty_scoresheet_generate, name='faculty_scoresheet_generate'),
    path('faculty/results-review/', faculty_results_review, name='faculty_results_review'),
    path('faculty/leaderboard/', faculty_leaderboard, name='faculty_leaderboard'),
    path(
        'faculty/profile/',
        RedirectView.as_view(pattern_name='faculty_dashboard', permanent=False),
        name='faculty_profile',
    ),
    # Legacy /tabulator/* aliases → Faculty portal (frontend/facultydash)
    path('tabulator/dashboard/', faculty_dashboard, name='tabulator_dashboard'),
    path('tabulator/assigned/', faculty_my_events, name='tabulator_assigned'),
    path('tabulator/scoresheets/', faculty_scoresheets, name='tabulator_scoresheets'),
    path('tabulator/ocr/', faculty_scoresheets, name='tabulator_ocr_upload'),
    path('tabulator/reports/', faculty_dashboard, name='tabulator_reports'),
    path('tabulator/tabulation/', faculty_results_review, name='tabulator_tabulation'),
    path('tabulator/encode/', faculty_results_review, name='tabulator_encode_score'),
    path('tabulator/encode/<int:sheet_id>/save/', tabulator_save_scores, name='tabulator_save_scores'),
    path('tabulator/reports/generate/', tabulator_generate_report, name='tabulator_generate_report'),
    path('tabulator/review/<int:sheet_id>/verify/', tabulator_verify_lock, name='tabulator_verify_lock'),
    path('tabulator/review/<int:sheet_id>/request-changes/', tabulator_request_changes, name='tabulator_request_changes'),
    path('tabulator/review/', faculty_results_review, name='tabulator_review'),
    path('tabulator/results/', faculty_results_review, name='tabulator_results'),
    path('tabulator/activity-logs/', faculty_dashboard, name='tabulator_activity_logs'),
    path('tabulator/activity-logs/feed/', tabulator_activity_logs_feed, name='tabulator_activity_logs_feed'),
    path('tabulator/pending-results/', faculty_results_review, name='tabulator_pending_results'),
    path('tabulator/approved-results/', faculty_results_review, name='tabulator_approved_results'),
    path('tabulator/result/<str:result_type>/<int:result_id>/approve/', tabulator_approve_result, name='tabulator_approve_result'),
    path('tabulator/result/<str:result_type>/<int:result_id>/reject/', tabulator_reject_result, name='tabulator_reject_result'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/reports/', admin_generate_report, name='admin_generate_report'),
    path('admin/departments/', admin_departments, name='admin_departments'),
    path('admin/teams/', admin_teams, name='admin_teams'),
    path('admin/candidates/', admin_candidates, name='admin_candidates'),
    path('admin/teams/create/', admin_create_team, name='admin_create_team'),
    path('admin/teams/<int:team_id>/view/', admin_view_team, name='admin_view_team'),
    path('admin/teams/<int:team_id>/edit/', admin_edit_team, name='admin_edit_team'),
    path('admin/teams/<int:team_id>/delete/', admin_delete_team, name='admin_delete_team'),
    path('admin/candidates/create/', admin_create_candidate, name='admin_create_candidate'),
    path('admin/candidates/<int:candidate_id>/view/', admin_view_candidate, name='admin_view_candidate'),
    path('admin/candidates/<int:candidate_id>/edit/', admin_edit_candidate, name='admin_edit_candidate'),
    path('admin/candidates/<int:candidate_id>/delete/', admin_delete_candidate, name='admin_delete_candidate'),
    path('admin/events/', admin_event_selector, name='admin_manage_events'),
    path('admin/events/match/', admin_match_events, name='admin_match_events'),
    path('admin/events/match/preview/', admin_match_event_preview, name='admin_match_event_preview'),
    path('admin/events/match/<int:event_id>/edit/', admin_match_events, name='admin_edit_match_event'),
    path('admin/events/match/<int:event_id>/view/', admin_match_event_detail, name='admin_view_match_event'),
    path('admin/events/match/<int:event_id>/delete/', admin_delete_match_event, name='admin_delete_match_event'),
    path('admin/events/criteria/', admin_criteria_events, name='admin_criteria_events'),
    path('admin/events/criteria/<int:event_id>/edit/', admin_criteria_events, name='admin_edit_criteria_event'),
    path('admin/events/criteria/<int:event_id>/view/', admin_criteria_event_detail, name='admin_view_criteria_event'),
    path('admin/events/criteria/<int:event_id>/delete/', admin_delete_criteria_event, name='admin_delete_criteria_event'),
    path('admin/events/<int:event_id>/edit/', admin_edit_event, name='admin_edit_event'),
    path('admin/events/<int:event_id>/delete/', admin_delete_event, name='admin_delete_event'),
    path('admin/events/bulk-delete/', admin_bulk_delete_events, name='admin_bulk_delete_events'),
    path('admin/events/tab/<str:tab_key>/create/', admin_tab_create, name='admin_tab_create'),
    path('admin/events/tab/<str:tab_key>/<int:record_id>/update/', admin_tab_update, name='admin_tab_update'),
    path('admin/events/tab/<str:tab_key>/<int:record_id>/delete/', admin_tab_delete, name='admin_tab_delete'),
    path('admin/manage-account/', admin_manage_account, name='admin_manage_account'),
    path('admin/manage-account/tabulator/', admin_tabulator_accounts, name='admin_tabulator_accounts'),
    path('admin/manage-account/judge-scorer/', admin_judge_scorer_accounts, name='admin_judge_scorer_accounts'),
    path('admin/scoresheets/', admin_scoresheets, name='admin_scoresheets'),
    path('admin/scoresheets/templates/', admin_scoresheet_template_save, name='admin_scoresheet_template_save'),
    path('admin/scoresheets/templates/<int:template_id>/delete/', admin_scoresheet_template_delete, name='admin_scoresheet_template_delete'),
    path('admin/scoresheets/templates/<int:template_id>/duplicate/', admin_scoresheet_template_duplicate, name='admin_scoresheet_template_duplicate'),
    path('admin/scoresheets/preview/', admin_scoresheet_preview, name='admin_scoresheet_preview'),
    path('admin/scoresheets/sample.pdf', admin_scoresheet_sample_pdf, name='admin_scoresheet_sample_pdf'),
    path('admin/brackets/', admin_brackets, name='admin_brackets'),
    path('admin/brackets/generate/', admin_generate_bracket, name='admin_generate_bracket'),
    path('admin/brackets/<int:event_id>/view/', admin_view_bracket, name='admin_view_bracket'),
    path('admin/brackets/<int:event_id>/delete/', admin_delete_bracket, name='admin_delete_bracket'),
    path('admin/brackets/<int:event_id>/teams/', admin_get_bracket_teams, name='admin_get_bracket_teams'),
    path('admin/departments/create/', admin_create_department, name='admin_create_department'),
    path('admin/departments/<int:dept_id>/view/', admin_view_department, name='admin_view_department'),
    path('admin/departments/<int:dept_id>/edit/', admin_edit_department, name='admin_edit_department'),
    path('admin/departments/<int:dept_id>/delete/', admin_delete_department, name='admin_delete_department'),
    path('admin/departments/bulk-delete/', admin_bulk_delete_departments, name='admin_bulk_delete_departments'),
    path('admin/accounts/create/', create_assignment_account, name='create_assignment_account'),
    path('admin/accounts/next-access-code/', next_assignment_access_code, name='next_assignment_access_code'),
    path('admin/accounts/<int:account_id>/update/', update_assignment_account, name='update_assignment_account'),
    path('admin/accounts/<int:account_id>/delete/', delete_assignment_account, name='delete_assignment_account'),
    path('admin/accounts/bulk-delete/', bulk_delete_assignment_accounts, name='bulk_delete_assignment_accounts'),
    path('super-admin/dashboard/', sa_dashboard, name='superadmin_dashboard'),
    path('super-admin/users/', superadmin_users, name='superadmin_users'),
    path('super-admin/users/<int:user_id>/', superadmin_user_detail, name='superadmin_user_detail'),
    path('super-admin/users/create/', superadmin_user_create, name='superadmin_user_create'),
    path('super-admin/users/<int:user_id>/update/', superadmin_user_update, name='superadmin_user_update'),
    path('super-admin/users/<int:user_id>/reset-password/', superadmin_user_reset_password, name='superadmin_user_reset_password'),
    path('super-admin/users/<int:user_id>/set-active/', superadmin_user_set_active, name='superadmin_user_set_active'),
    path('super-admin/users/<int:user_id>/delete/', superadmin_user_delete, name='superadmin_user_delete'),
    path('super-admin/events/', superadmin_event_monitoring, name='superadmin_event_monitoring'),
    path('super-admin/events/<int:event_id>/', superadmin_event_detail, name='superadmin_event_detail'),
    path('super-admin/leaderboard/', superadmin_leaderboard, name='superadmin_leaderboard'),
    path('super-admin/leaderboard/export/', superadmin_leaderboard_export, name='superadmin_leaderboard_export'),
    path('super-admin/settings/', superadmin_settings, name='superadmin_settings'),
    path('super-admin/settings/save/', superadmin_settings_save, name='superadmin_settings_save'),
    path('super-admin/profile/', superadmin_profile, name='superadmin_profile'),
    path('super-admin/profile/update/', superadmin_profile_update, name='superadmin_profile_update'),
    path('super-admin/profile/change-password/', superadmin_change_password, name='superadmin_change_password'),
    path('super-admin/admins/', RedirectView.as_view(pattern_name='superadmin_users', permanent=False), name='superadmin_admins'),
    path('super-admin/reports/', superadmin_reports, name='superadmin_reports'),
    path('super-admin/reports/generate/', generate_superadmin_report, name='generate_superadmin_report'),
    path('super-admin/activity-logs/', sa_activity_logs, name='superadmin_activity_logs'),
    path('super-admin/audit-logs/', sa_activity_logs, name='superadmin_audit_logs'),
    path('super-admin/admins/create/', create_admin, name='create_admin'),
    path('super-admin/admins/<int:admin_id>/update/', update_admin, name='update_admin'),
    path('super-admin/admins/<int:admin_id>/delete/', delete_admin, name='delete_admin'),
    path('super-admin/admins/<int:admin_id>/activate/', activate_admin, name='activate_admin'),
    path('super-admin/admins/<int:admin_id>/deactivate/', deactivate_admin, name='deactivate_admin'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
