"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .api_views import health_check
from .views import (
    admin_brackets,
    admin_generate_bracket,
    admin_view_bracket,
    admin_delete_bracket,
    admin_get_bracket_teams,
    admin_departments,
    admin_teams,
    admin_candidates,
    admin_create_team,
    admin_view_team,
    admin_edit_team,
    admin_delete_team,
    admin_create_candidate,
    admin_view_candidate,
    admin_edit_candidate,
    admin_delete_candidate,
    admin_dashboard,
    admin_generate_report,
    admin_bulk_delete_events,
    admin_delete_event,
    admin_edit_event,
    admin_tab_create,
    admin_tab_update,
    admin_tab_delete,
    admin_manage_account,
    admin_tabulator_accounts,
    admin_judge_scorer_accounts,
    admin_manage_events,
    activate_admin,
    admin_create_department,
    admin_view_department,
    admin_edit_department,
    admin_delete_department,
    admin_bulk_delete_departments,
    create_assignment_account,
    next_assignment_access_code,
    create_admin,
    deactivate_admin,
    delete_assignment_account,
    bulk_delete_assignment_accounts,
    delete_admin,
    login_view,
    logout_view,
    superadmin_activity_logs,
    superadmin_admins,
    superadmin_dashboard,
    superadmin_reports,
    generate_superadmin_report,
    tabulator_assigned_events,
    tabulator_dashboard,
    tabulator_scoresheets,
    tabulator_ocr_upload,
    tabulator_reports,
    tabulator_tabulation,
    tabulator_encode_score,
    tabulator_save_scores,
    tabulator_generate_report,
    tabulator_verify_lock,
    tabulator_request_changes,
    tabulator_review,
    tabulator_results,
    tabulator_activity_logs,
    tabulator_activity_logs_feed,
    tabulator_approve_result,
    tabulator_reject_result,
    tabulator_pending_results,
    tabulator_approved_results,
    update_assignment_account,
    update_admin,
)

urlpatterns = [
    path('api/health/', health_check, name='health_check'),
    path('api/auth/', include('accounts.urls')),
    path('api/events/', include('events.api_urls')),
    path('', login_view, name='home'),
    path('login/', login_view, name='login'),
    path('tabulator/dashboard/', tabulator_dashboard, name='tabulator_dashboard'),
    path('tabulator/assigned/', tabulator_assigned_events, name='tabulator_assigned'),
    path('tabulator/scoresheets/', tabulator_scoresheets, name='tabulator_scoresheets'),
    path('tabulator/ocr/', tabulator_ocr_upload, name='tabulator_ocr_upload'),
    path('tabulator/reports/', tabulator_reports, name='tabulator_reports'),
    path('tabulator/tabulation/', tabulator_tabulation, name='tabulator_tabulation'),
    path('tabulator/encode/', tabulator_encode_score, name='tabulator_encode_score'),
    path('tabulator/encode/<int:sheet_id>/save/', tabulator_save_scores, name='tabulator_save_scores'),
    path('tabulator/reports/generate/', tabulator_generate_report, name='tabulator_generate_report'),
    path('tabulator/review/<int:sheet_id>/verify/', tabulator_verify_lock, name='tabulator_verify_lock'),
    path('tabulator/review/<int:sheet_id>/request-changes/', tabulator_request_changes, name='tabulator_request_changes'),
    path('tabulator/review/', tabulator_review, name='tabulator_review'),
    path('tabulator/results/', tabulator_results, name='tabulator_results'),
    path('tabulator/activity-logs/', tabulator_activity_logs, name='tabulator_activity_logs'),
    path('tabulator/activity-logs/feed/', tabulator_activity_logs_feed, name='tabulator_activity_logs_feed'),
    path('tabulator/pending-results/', tabulator_pending_results, name='tabulator_pending_results'),
    path('tabulator/approved-results/', tabulator_approved_results, name='tabulator_approved_results'),
    path('tabulator/result/<str:result_type>/<int:result_id>/approve/', tabulator_approve_result, name='tabulator_approve_result'),
    path('tabulator/result/<str:result_type>/<int:result_id>/reject/', tabulator_reject_result, name='tabulator_reject_result'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/reports/', admin_generate_report, name='admin_generate_report'),
    path('admin/departments/', admin_departments, name='admin_departments'),
    path('admin/teams/', admin_teams, name='admin_teams'),
    path('admin/candidates/', admin_candidates, name='admin_candidates'),
    path('admin/teams/create/', admin_create_team, name='admin_create_team'),
    path('admin/teams/<int:team_id>/view/', admin_view_team, name='admin_view_team'),
    path('admin/teams/<int:team_id>/edit/', admin_edit_team, name='admin_edit_team'),
    path('admin/teams/<int:team_id>/delete/', admin_delete_team, name='admin_delete_team'),
    path('admin/candidates/create/', admin_create_candidate, name='admin_create_candidate'),
    path('admin/candidates/<int:candidate_id>/view/', admin_view_candidate, name='admin_view_candidate'),
    path('admin/candidates/<int:candidate_id>/edit/', admin_edit_candidate, name='admin_edit_candidate'),
    path('admin/candidates/<int:candidate_id>/delete/', admin_delete_candidate, name='admin_delete_candidate'),
    path('admin/events/', admin_manage_events, name='admin_manage_events'),
    path('admin/events/<int:event_id>/edit/', admin_edit_event, name='admin_edit_event'),
    path('admin/events/<int:event_id>/delete/', admin_delete_event, name='admin_delete_event'),
    path('admin/events/bulk-delete/', admin_bulk_delete_events, name='admin_bulk_delete_events'),
    path('admin/events/tab/<str:tab_key>/create/', admin_tab_create, name='admin_tab_create'),
    path('admin/events/tab/<str:tab_key>/<int:record_id>/update/', admin_tab_update, name='admin_tab_update'),
    path('admin/events/tab/<str:tab_key>/<int:record_id>/delete/', admin_tab_delete, name='admin_tab_delete'),
    path('admin/manage-account/', admin_manage_account, name='admin_manage_account'),
    path('admin/manage-account/tabulator/', admin_tabulator_accounts, name='admin_tabulator_accounts'),
    path('admin/manage-account/judge-scorer/', admin_judge_scorer_accounts, name='admin_judge_scorer_accounts'),
    path('admin/brackets/', admin_brackets, name='admin_brackets'),
    path('admin/brackets/generate/', admin_generate_bracket, name='admin_generate_bracket'),
    path('admin/brackets/<int:event_id>/view/', admin_view_bracket, name='admin_view_bracket'),
    path('admin/brackets/<int:event_id>/delete/', admin_delete_bracket, name='admin_delete_bracket'),
    path('admin/brackets/<int:event_id>/teams/', admin_get_bracket_teams, name='admin_get_bracket_teams'),
    path('admin/departments/create/', admin_create_department, name='admin_create_department'),
    path('admin/departments/<int:dept_id>/view/', admin_view_department, name='admin_view_department'),
    path('admin/departments/<int:dept_id>/edit/', admin_edit_department, name='admin_edit_department'),
    path('admin/departments/<int:dept_id>/delete/', admin_delete_department, name='admin_delete_department'),
    path('admin/departments/bulk-delete/', admin_bulk_delete_departments, name='admin_bulk_delete_departments'),
    path('admin/accounts/create/', create_assignment_account, name='create_assignment_account'),
    path('admin/accounts/next-access-code/', next_assignment_access_code, name='next_assignment_access_code'),
    path('admin/accounts/<int:account_id>/update/', update_assignment_account, name='update_assignment_account'),
    path('admin/accounts/<int:account_id>/delete/', delete_assignment_account, name='delete_assignment_account'),
    path('admin/accounts/bulk-delete/', bulk_delete_assignment_accounts, name='bulk_delete_assignment_accounts'),
    path('super-admin/dashboard/', superadmin_dashboard, name='superadmin_dashboard'),
    path('super-admin/admins/', superadmin_admins, name='superadmin_admins'),
    path('super-admin/reports/', superadmin_reports, name='superadmin_reports'),
    path('super-admin/reports/generate/', generate_superadmin_report, name='generate_superadmin_report'),
    path('super-admin/activity-logs/', superadmin_activity_logs, name='superadmin_activity_logs'),
    path('super-admin/admins/create/', create_admin, name='create_admin'),
    path('super-admin/admins/<int:admin_id>/update/', update_admin, name='update_admin'),
    path('super-admin/admins/<int:admin_id>/delete/', delete_admin, name='delete_admin'),
    path('super-admin/admins/<int:admin_id>/activate/', activate_admin, name='activate_admin'),
    path('super-admin/admins/<int:admin_id>/deactivate/', deactivate_admin, name='deactivate_admin'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
